# Generated by Django 4.2 on 2023-05-09 19:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_rename_owner_location_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Weather',
        ),
    ]
