# Generated by Django 4.2 on 2023-05-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_tag_locationtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
