# Generated by Django 4.2 on 2023-05-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_delete_locationtag_delete_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'locations'},
        ),
    ]
