# Generated by Django 4.2 on 2023-05-15 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
    ]
