# Generated by Django 4.2 on 2023-05-15 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_location_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
    ]
