# Generated by Django 4.2 on 2023-05-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
